version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile    # Path to your Dockerfile
    ports:
      - "8080:80"              # Map port 80 in the container to 8080 on the host
    volumes:
      - ./app:/var/www/html    # Mount the app directory for live updates
      - ./vendor:/var/www/vendor
    depends_on:
      - db                     # Ensure the database container starts first

  db:
    image: mysql:5.7
    container_name: mysql
    platform: linux/amd64  # Force x86_64 compatibility
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_project
    volumes:
      - db_data:/var/lib/mysql # Persistent database storage
    ports:
      - "3307:3306"



volumes:
  db_data:                     # Define a named volume for MySQL data persistence
